# ????
server:
  port: 3000
  servlet:
    context-path: /api
# ?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: 284347Qa.
  profiles:
    active: local
# ????
knife4j:
  enable: true
  openapi:
    title: ????
    group:
      default:
        group-name: ????
        api-rule: package
        api-rule-resources:
          - com.haigui.haigui.controller